version: "3"

volumes:
  meow_volume: {}

services:
  frontend:
    build:
      context: .
      dockerfile: ./meow/frontend/Dockerfile
    volumes:
      - meow_volume:/frontend
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: honcho start -f Procfile.dev
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db
      - redis
      - frontend
    volumes:
      - meow_volume:/django
  db:
    image: postgres:latest
  redis:
    image: redis:alpine
