version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: ./meow/frontend/Dockerfile
  django:
    build: .
    image: meow
    command: honcho start -f Procfile.dev
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/meow
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"