version: '3'

services:
  web:
    build: .
    image: meow
    command: honcho start -f Procfile.dev
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/meow
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"