version: '2'
services:
  web:
    build: .
    image: meow
    restart: always
    entrypoint: /meow/entrypoint.sh
    command: honcho start -f Procfile
    depends_on:
      - db
      - redis
    
  db:
    image: postgres:latest
    volumes: 
      - data:/var/lib/postgresql/
    restart: always

  redis:
    restart: always
    image: redis:alpine

volumes:
  data:
    driver: rancher-nfs